In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [3]:
data = pd.read_csv('102MUL~1_exercise.CSV')

In [6]:
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [7]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

In [8]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

In [9]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [10]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [11]:
reg.intercept_

0.29603261264909353

In [13]:
reg.score(x,y)

0.40668119528142815

### Formula for Adjusted R^2

$R^2_{adj.} = 1 - (1-R^2)*\frac{n-1}{n-p-1}$

In [15]:
x.shape

(84, 2)

In [16]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.39203134825134

In [17]:
# There are different ways to solve this problem
# To make it as easy and interpretable as possible, we have preserved the original code
def adj_r2(x,y):
    r2 = reg.score(x,y)
    n = x.shape[0]
    p = x.shape[1]
    adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
    return adjusted_r2

In [19]:
# Here's the result
adj_r2(x,y)

0.39203134825134

how to detect variables which are unneeded in a model?

### Feature selection  simplifies models 

### in statsmodel, we were given the p-value which can be used to determine whether the independent variables were relevant for the model.

### IF A VARIABLE HAS A P-VALUE > 0.05, WE CAN DISREGARD IT. 

## feature_selecton.f_regression
f-regression creates simple linear regressions of each feature and the dependent variable. 

In [22]:
from sklearn.feature_selection import f_regression

In [23]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

### array([56.04804786,  0.17558437]),   F statstics 
### array([7.19951844e-11, 6.76291372e-01])   p-values 

In [25]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [26]:
p_values.round(3)

array([0.   , 0.676])

SAT is a useful variable, random123 is useless

these are the univariate p-values reached from simple linear models. they do not reflect the interconnection of the features in our multople linear regression.

## Creating a summary table

In [27]:
reg_summary = pd.DataFrame(data=['SAT', 'Rand 1,2,3'], columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [28]:
reg_summary = pd.DataFrame(data=x.columns.values, columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [29]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [30]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

Rand 123 doesn't contribute to our model and should be removed 

p-values are one of the best ways to determine if a variable is redundant, but they provide noinformaton whatsoever about HOW USEFUL a variable is. 

two values both with 000 p-values arent necessrily equally important.

In [35]:
data = pd.read_csv('REAL_E~1.CSV')
data.head()

FileNotFoundError: [Errno 2] File b'REAL_E~1.CSV' does not exist: b'REAL_E~1.CSV'